
services:

  postgres:
    image: postgres:latest
    container_name: portfolio_service_postgres
    ports:
      - "6000:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: portfolio_service_db
      PGDATA: /var/lib/data/postgresql

  portfolio-service:
    build:
      context: portfolio-service
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - postgres
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/portfolio_service_db

  gateway-server:
    build:
      context: gateway-server
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
    depends_on:
      - postgres
      - portfolio-service
    restart: unless-stopped